export const ADD_EXPENSE = 'ADD_EXPENSE';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
export const SET_EXPENSES = 'SET_EXPENSES';

const expensesActionTypes = {
    POST_NEW_EXPANSE_START: 'POST_NEW_EXPANSE_START',
    POST_NEW_EXPANSE_SUCCESS: 'POST_NEW_EXPANSE_SUCCESS',
    POST_NEW_EXPANSE_FAILURE: 'POST_NEW_EXPANSE_FAILURE',
    CLEAR_POST_NEW_EXPANSE: 'CLEAR_POST_NEW_EXPANSE',
    // FETCH_JOBS_START: 'FETCH_JOBS_START',
    // FETCH_JOBS_SUCCESS: 'FETCH_JOBS_S UCCESS',
    // FETCH_JOBS_FAILURE: 'FETCH_JOBS_FAILURE',

    // FETCH_CANDIDATE_JOBS_START: 'FETCH_CANDIDATE_JOBS_START',
    // FETCH_CANDIDATE_JOBS_SUCCESS: 'FETCH_CANDIDATE_JOBS_SUCCESS',
    // FETCH_CANDIDATE_JOBS_FAILURE: 'FETCH_CANDIDATE_JOBS_FAILURE',

    // FETCH_RECRUITER_JOBS_START: 'FETCH_RECRUITER_JOBS_START',
    // FETCH_RECRUITER_JOBS_SUCCESS: 'FETCH_RECRUITER_JOBS_SUCCESS',
    // FETCH_RECRUITER_JOBS_FAILURE: 'FETCH_RECRUITER_JOBS_FAILURE',

    // FETCH_APPLIED_JOBS_START: 'FETCH_APPLIED_JOBS_START',
    // FETCH_APPLIED_JOBS_SUCCESS: 'FETCH_APPLIED_JOBS_SUCCESS',
    // FETCH_APPLIED_JOBS_FAILURE: 'FETCH_APPLIED_JOBS_FAILURE',

    // POST_NEW_JOB_START: 'POST_NEW_JOB_START',
    // POST_NEW_JOB_SUCCESS: 'POST_NEW_JOB_SUCCESS',
    // POST_NEW_JOB_FAILURE: 'POST_NEW_JOB_FAILURE',
    // CLEAR_POST_NEW_JOB: 'CLEAR_POST_NEW_JOB',

    // APPLY_NEW_JOB_START: 'APPLY_NEW_JOB_START',
    // APPLY_NEW_JOB_SUCCESS: 'APPLY_NEW_JOB_SUCCESS',
    // APPLY_NEW_JOB_FAILURE: 'APPLY_NEW_JOB_FAILURE',

    // FETCH_APPLICATIONS_FOR_A_JOB_START: 'FETCH_APPLICATIONS_FOR_A_JOB_START',
    // FETCH_APPLICATIONS_FOR_A_JOB_SUCCESS: 'FETCH_APPLICATIONS_FOR_A_JOB_SUCCESS',
    // FETCH_APPLICATIONS_FOR_A_JOB_FAILURE: 'FETCH_APPLICATIONS_FOR_A_JOB_FAILURE',

    CLEAR_ERRORS: 'CLEAR_ERRORS',
}

export default expensesActionTypes;
